services:
  - type: web
    name: examen02-dvd
    runtime: node
    buildCommand: npm install && npx nest build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
